const genres = [
  { id: 1, name: "Fantasy" },
  { id: 2, name: "Science Fiction" },
  { id: 3, name: "Dystopian" },
  { id: 4, name: "Adventure" },
  { id: 5, name: "Action" },
  { id: 6, name: "Mystery" },
  { id: 7, name: "Thriller" },
  { id: 8, name: "Crime" },
  { id: 9, name: "Horror" },
  { id: 10, name: "Historical Fiction" },
  { id: 11, name: "Romance" },
  { id: 12, name: "Contemporary" },
  { id: 13, name: "Drama" },
  { id: 14, name: "Satire" },
  { id: 15, name: "Magical Realism" },
  { id: 16, name: "Graphic Novel" },
  { id: 17, name: "Short Stories" },
  { id: 18, name: "Young Adult (YA)" },
  { id: 19, name: "New Adult" },
  { id: 20, name: "Children’s Fiction" },
  { id: 21, name: "Literary Fiction" },
  { id: 22, name: "Classic" },
  { id: 23, name: "Memoir" },
  { id: 24, name: "Biography" },
  { id: 25, name: "Autobiography" },
  { id: 26, name: "Self-Help" },
  { id: 27, name: "Health & Wellness" },
  { id: 28, name: "True Crime" },
  { id: 29, name: "Essays" },
  { id: 30, name: "Poetry" },
  { id: 31, name: "Spirituality" },
  { id: 32, name: "Religion" },
  { id: 33, name: "Philosophy" },
  { id: 34, name: "Science & Nature" },
  { id: 35, name: "Travel" },
  { id: 36, name: "Guide / How-To" },
  { id: 37, name: "Cookbooks" },
  { id: 38, name: "Art & Photography" },
  { id: 39, name: "History" },
  { id: 40, name: "Politics" },
  { id: 41, name: "Business & Economics" },
  { id: 42, name: "Technology" },
  { id: 43, name: "Education" },
  { id: 44, name: "Parenting & Family" },
  { id: 45, name: "Sports & Recreation" },
  { id: 46, name: "Humor" },
  { id: 47, name: "Western" },
  { id: 48, name: "Paranormal" },
  { id: 49, name: "Urban Fantasy" },
  { id: 50, name: "Chick Lit" }
];

export default genres;
