const genresList = [
  { value: 'Fantasy', label: 'Fantasy' },
  { value: 'Science Fiction', label: 'Science Fiction' },
  { value: 'Dystopian', label: 'Dystopian' },
  { value: 'Adventure', label: 'Adventure' },
  { value: 'Action', label: 'Action' },
  { value: 'Mystery', label: 'Mystery' },
  { value: 'Thriller', label: 'Thriller' },
  { value: 'Crime', label: 'Crime' },
  { value: 'Horror', label: 'Horror' },
  { value: 'Historical Fiction', label: 'Historical Fiction' },
  { value: 'Romance', label: 'Romance' },
  { value: 'Contemporary', label: 'Contemporary' },
  { value: 'Drama', label: 'Drama' },
  { value: 'Satire', label: 'Satire' },
  { value: 'Magical Realism', label: 'Magical Realism' },
  { value: 'Graphic Novel', label: 'Graphic Novel' },
  { value: 'Short Stories', label: 'Short Stories' },
  { value: 'Young Adult (YA)', label: 'Young Adult (YA)' },
  { value: 'New Adult', label: 'New Adult' },
  { value: 'Children’s Fiction', label: 'Children’s Fiction' },
  { value: 'Literary Fiction', label: 'Literary Fiction' },
  { value: 'Classic', label: 'Classic' },
  { value: 'Memoir', label: 'Memoir' },
  { value: 'Biography', label: 'Biography' },
  { value: 'Autobiography', label: 'Autobiography' },
  { value: 'Self-Help', label: 'Self-Help' },
  { value: 'Health & Wellness', label: 'Health & Wellness' },
  { value: 'True Crime', label: 'True Crime' },
  { value: 'Essays', label: 'Essays' },
  { value: 'Poetry', label: 'Poetry' },
  { value: 'Spirituality', label: 'Spirituality' },
  { value: 'Religion', label: 'Religion' },
  { value: 'Philosophy', label: 'Philosophy' },
  { value: 'Science & Nature', label: 'Science & Nature' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Guide / How-To', label: 'Guide / How-To' },
  { value: 'Cookbooks', label: 'Cookbooks' },
  { value: 'Art & Photography', label: 'Art & Photography' },
  { value: 'History', label: 'History' },
  { value: 'Politics', label: 'Politics' },
  { value: 'Business & Economics', label: 'Business & Economics' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Education', label: 'Education' },
  { value: 'Parenting & Family', label: 'Parenting & Family' },
  { value: 'Sports & Recreation', label: 'Sports & Recreation' },
  { value: 'Humor', label: 'Humor' },
  { value: 'Western', label: 'Western' },
  { value: 'Paranormal', label: 'Paranormal' },
  { value: 'Urban Fantasy', label: 'Urban Fantasy' },
  { value: 'Chick Lit', label: 'Chick Lit' },
];

export default genresList;
